### PR TITLE
Refactor the poll results view

### PR DESCRIPTION
**Pull request by juho-jaakkola**
- Moves inline code into Poll class methods
- Makes the result view more responsive
- Makes the translation strings more customizable
- Replaces custom javascript with Elgg's built-in toggle feature

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Before and after images:

before

---------------------------

after

**Comment by juho-jaakkola** [comment]
The ```<progress>``` element isn't necessarily very good looking by default in all browsers. Then again it would be impossible anyway to style it so that it would fit every single Elgg site out there.

Therefore I'm suggesting poll to use the non-styled element and letting each site's theme to take care of styling if necessary.

**Comment by iionly** [comment]
I'm a bit worried about browser support of the progress element. I had to check up what it is in the first place as I had never come across it before. Not that I would worry about IE support myself but it seems the progress element is only supported since IE10 (even then only partly as it seems). I know that the upcoming Elgg 1.10 will drop support of IE8. But right now the Poll plugin is still supposed to work on Elgg 1.9 and even on dropping support of IE8 with Elgg 1.10 there's still IE9 to consider from a plugin BC perspective. I don't know if it has been decided on a polyfill support in Elgg core. I don't know but it might be too soon to rely on this html5 element already.

Regarding the look I would like to provide at least some basic styling that looks kind of okay and fits with the default Elgg theme regarding colors (rather Aalborg theme actually). I think the color, background color and border could be defined via CSS (maybe using the colors that have already been used up to now). I don't know if I like the vertical lines in the progress bar. They don't have any real informative value anyway as the filling of the bars is not based on an absolute value but rather based on the current number of total votes.

Due to the "Work in progress - requires more testing!" above I'm not sure if you are done with the code changes already and just wait for further testing (by me?). Anyway, I'm not merging just yet mainly due the concerns regarding browser compatibility - awaiting to hear what you think.

**Comment by juho-jaakkola** [comment]
Now that I tested it on other browsers, I see that the ```<progress>``` bars really do not look good on Firefox. Also it would be semantically correct to use the  ```<meter>``` tag instead. It's however not yet properly supported even by IE11.

I'm going to revert back the original ```<div>``` elements.

**Comment by juho-jaakkola** [comment]
Done

**Pull request merged**
