### PR TITLE
Fixes the isOpen() method that had the return value backwards

### PR DESCRIPTION
**Pull request by juho-jaakkola**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Sorry about that. I clearly need to be more careful when refactoring.

**Comment by iionly** [comment]
If I would have more free time I would help with testing. Unfortunately, I'm just too busy with working on other plugins currently. Once you think that you're done with refactoring I will surely help with testing.

**Comment by juho-jaakkola** [comment]
Is there any chance I could get a write access to the repo? It would make the refactoring much faster and easier.

I would of course make new features through PRs so you'd have a chance to affect or block them if necessary.

**Comment by iionly** [comment]
@juho-jaakkola I've made you a collaborator for the repo. Do you have write access now?

**Comment by juho-jaakkola** [comment]
Yes, thanks!

**Pull request merged**
